export const LATEST_LISTING_FAILURE = "LATEST_LISTING_FAILURE";
export const REQUEST_LATEST_LISTING = "REQUEST_LATEST_LISTING";
export const LATEST_LISTING_SUCCESS = "LATEST_LISTING_SUCCESS";
export const CONVERT_LATEST_LISTING = "CONVERT_LATEST_LISTING";
export const TOGGLE_CONVERSION_CURRENCY = "TOGGLE_CONVERSION_CURRENCY";
export const TOGGLE_APP_THEME = "TOGGLE_APP_THEME";